#!/usr/bin/env node
/**
 * sync-skills.mjs
 *
 * Mirror every plugin-bundled skill into the repo-root `/skills/<name>/`
 * directory so that `npx openskills install <org>/<repo>` discovers them at the
 * conventional location.
 *
 * Canonical source of truth lives at:
 *   plugins/<plugin-name>/skills/<skill-name>/
 *
 * Repo-root mirror (generated by this script) lives at:
 *   skills/<skill-name>/
 *
 * Each mirror is byte-identical to its canonical. Sibling resources
 * (references/, scripts/, assets/, etc.) are copied verbatim.
 *
 * Usage:
 *   node scripts/sync-skills.mjs               # write mode: regenerate skills/
 *   node scripts/sync-skills.mjs --check       # CI mode: exit 1 on drift, 0 on clean
 *   node scripts/sync-skills.mjs --verbose     # log every file copied/compared
 *
 * CI integration:
 *   .github/workflows/skills-sync-check.yml runs this in --check mode on every
 *   PR. The check fails if (a) skills/ is missing a canonical mirror,
 *   (b) skills/ contains a file that diverges from its canonical, or
 *   (c) skills/ contains an orphan folder with no canonical source.
 *
 * Name collisions:
 *   Skill names must be globally unique across all plugins in this repo.
 *   The script aborts with a non-zero exit if two plugins ship the same
 *   skill name.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, '..');
const args = process.argv.slice(2);
const CHECK = args.includes('--check');
const VERBOSE = args.includes('--verbose');

function log(...a) { if (VERBOSE) console.log('   ', ...a); }
function err(...a) { console.error(...a); }

// ---------- 1. discover plugin sources from marketplace.json ----------
const manifestPath = path.join(REPO, '.claude-plugin', 'marketplace.json');
if (!fs.existsSync(manifestPath)) {
  err('FATAL: .claude-plugin/marketplace.json missing');
  process.exit(2);
}
const marketplace = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
if (!Array.isArray(marketplace.plugins)) {
  err('FATAL: marketplace.json has no plugins array');
  process.exit(2);
}

// ---------- 2. enumerate skills under each plugin ----------
const skillMap = new Map(); // skill-name → { source: abs-path, plugin: plugin-name }
for (const plugin of marketplace.plugins) {
  if (!plugin.source) continue;
  const pluginRoot = path.resolve(REPO, plugin.source);
  const skillsDir = path.join(pluginRoot, 'skills');
  if (!fs.existsSync(skillsDir)) {
    log(`(${plugin.name}: no skills/ dir, skipping)`);
    continue;
  }
  const entries = fs.readdirSync(skillsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const skillSourcePath = path.join(skillsDir, entry.name);
    if (!fs.existsSync(path.join(skillSourcePath, 'SKILL.md'))) {
      log(`(${plugin.name}/${entry.name}: no SKILL.md, skipping)`);
      continue;
    }
    if (skillMap.has(entry.name)) {
      const prior = skillMap.get(entry.name);
      err(`FATAL: skill name collision — "${entry.name}" exists in:`);
      err(`  - ${prior.plugin} (${path.relative(REPO, prior.source)})`);
      err(`  - ${plugin.name} (${path.relative(REPO, skillSourcePath)})`);
      err('Rename one of them; skill names must be globally unique.');
      process.exit(2);
    }
    skillMap.set(entry.name, { source: skillSourcePath, plugin: plugin.name });
  }
}

// ---------- 3. sync or check ----------
const mirrorRoot = path.join(REPO, 'skills');
const drift = [];

function dirByteEqual(a, b) {
  if (!fs.existsSync(a) || !fs.existsSync(b)) return false;
  const aFiles = listFilesRecursive(a);
  const bFiles = listFilesRecursive(b);
  if (aFiles.length !== bFiles.length) return false;
  for (let i = 0; i < aFiles.length; i++) {
    if (aFiles[i] !== bFiles[i]) return false;
  }
  for (const rel of aFiles) {
    const aBuf = fs.readFileSync(path.join(a, rel));
    const bBuf = fs.readFileSync(path.join(b, rel));
    if (!aBuf.equals(bBuf)) return false;
  }
  return true;
}

function listFilesRecursive(root, prefix = '') {
  const out = [];
  for (const entry of fs.readdirSync(root, { withFileTypes: true }).sort((x, y) => x.name.localeCompare(y.name))) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    const full = path.join(root, entry.name);
    if (entry.isDirectory()) {
      out.push(...listFilesRecursive(full, rel));
    } else if (entry.isFile()) {
      out.push(rel);
    }
  }
  return out;
}

function copyDirRecursive(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const dstPath = path.join(dst, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, dstPath);
    } else if (entry.isFile()) {
      fs.copyFileSync(srcPath, dstPath);
      // Preserve executable bit (for renderer.js etc.)
      const mode = fs.statSync(srcPath).mode;
      fs.chmodSync(dstPath, mode);
    }
  }
}

for (const [name, { source, plugin }] of skillMap) {
  const target = path.join(mirrorRoot, name);
  if (CHECK) {
    if (!dirByteEqual(source, target)) {
      drift.push({ name, kind: 'out-of-sync', source: path.relative(REPO, source), plugin });
    } else {
      log(`✓ ${name} (from ${plugin})`);
    }
  } else {
    if (fs.existsSync(target)) fs.rmSync(target, { recursive: true, force: true });
    copyDirRecursive(source, target);
    log(`→ ${name} mirrored from ${plugin}`);
  }
}

// ---------- 4. orphan detection: skills/ dirs with no canonical source ----------
if (fs.existsSync(mirrorRoot)) {
  for (const entry of fs.readdirSync(mirrorRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (skillMap.has(entry.name)) continue;
    const orphanPath = path.join(mirrorRoot, entry.name);
    if (CHECK) {
      drift.push({ name: entry.name, kind: 'orphan', source: '(none)', plugin: '(none)' });
    } else {
      fs.rmSync(orphanPath, { recursive: true, force: true });
      log(`✗ removed orphan ${entry.name}`);
    }
  }
}

// ---------- 5. report ----------
if (CHECK) {
  if (drift.length === 0) {
    console.log(`✓ skills/ in sync — ${skillMap.size} skill${skillMap.size === 1 ? '' : 's'} match their plugin canonicals`);
    process.exit(0);
  }
  err(`✗ skills/ out of sync — ${drift.length} item${drift.length === 1 ? '' : 's'}:`);
  for (const d of drift) {
    err(`  - ${d.name} [${d.kind}]${d.source !== '(none)' ? ` ← ${d.source}` : ''}`);
  }
  err('');
  err('Fix: run  node scripts/sync-skills.mjs');
  process.exit(1);
}

console.log(`✓ synced ${skillMap.size} skill${skillMap.size === 1 ? '' : 's'} to skills/:`);
for (const [name, { plugin }] of skillMap) {
  console.log(`  - skills/${name}  (from plugins/${plugin}/)`);
}
